### ISSUE TITLE
Weird order of buttons

### ISSUE THREAD

**Issue by TheMrPhantom** [FIUS/Verleihsystem-TTF#94] opened 2019-05-01 21:59 UTC
Buttons in front menu are aligned vertical after login.
Chrome Browser.
Is temporarily fixed by reloading the page.

**Comment by mee4895** [comment] 2019-05-02 20:08
Can't reproduce please clarify the steps or find others with the same error!

**Comment by mee4895** [comment] 2019-05-02 20:09
Maybe this is fixed by #88 ???

**Closed** 2019-12-07 16:31 UTC
Labels: Bug, UI, needmoreinfo
